### ISSUE TITLE
make_credential_user_entity - Optional entry icon not recognized.

### ISSUE THREAD

**Issue by StarGate01** [BryanJacobs/FIDO2Applet#19]
The Google test suite (https://github.com/google/CTAP2-test-tool) found a bug.

According to the CTAP2.1 spec, §6.1 (https://fidoalliance.org/specs/fido-v2.1-rd-20210309/fido-client-to-authenticator-protocol-v2.1-rd-20210309.html#authenticatorMakeCredential):

> Note: [[WebAuthn-2]](https://fidoalliance.org/specs/fido-v2.1-rd-20210309/fido-client-to-authenticator-protocol-v2.1-rd-20210309.html#biblio-webauthn-2) has removed the optional icon member. Authenticators MUST not error if the icon member is present, they may optionally not store this value.

Test output:

```
Failed test: Tests bad parameters in user parameter of MakeCredential. (id: make_credential_user_entity) - Optional entry icon not recognized.
The failing error code is `CTAP1_ERR_INVALID_PARAMETER`.
```

Log trace from the bridge:

```
INFO:bridge:Transmitting CTAP command: AUTHN_MakeCredential
DEBUG:bridge:CBOR command payload: {
  "1": "h'cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
  "2": {
    "id": "make_credential_user_entity.example.com"
  },
  "3": {
    "id": "h'1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d",
    "icon": "http://icon.png"
  },
  "4": [
    {
      "alg": -7,
      "type": "public-key"
    }
  ]
}
INFO:bridge:CTAP command requires user presence, sending 'waiting for acknowledgment' status
INFO:bridge:APDU command: 176 bytes data
DEBUG:bridge:APDU command: DATA=801000000000a701a4015820cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd02a162696478276d616b655f63726564656e7469616c5f757365725f656e746974792e6578616d706c652e636f6d03a262696458201d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d6469636f6e6f687474703a2f2f69636f6e2e706e670481a263616c672664747970656a7075626c69632d6b65790000
INFO:bridge:APDU response: SW1=0x90, SW2=0x0, 1 bytes data
DEBUG:bridge:APDU response: DATA=02
ERROR:bridge:CTAP error: CTAP_STATUS_CODE.CTAP1_ERR_INVALID_PARAMETER
ERROR:ctap.auth:Exception from authenticator: CTAP error response from authenticator
```

**Comment by BryanJacobs** [comment]
The error here is that the user entry is missing the `name` (and `displayName`) parameters.

Both are required (not optional) at https://w3c.github.io/webauthn/#dictdef-publickeycredentialuserentity , and argument 3 to a makeCredential is a PublicKeyCredentialUserEntity. But the CTAP standard says the name is optional so I will relax the check.

Icons are accepted (and ignored) just fine.
