### ISSUE TITLE
About the encrypt(shared secret, LEFT(SHA-256(PIN), 16)) in traffic

### ISSUE THREAD

**Issue by nuno0529** [BryanJacobs/FIDO2Applet#2]
https://github.com/BryanJacobs/FIDO2Applet/blob/main/docs/security.md?plain=1#L111

The MITM traffic can just get the 16-bytes with ECDH's shared-secret still, I think this treat should be belong to malware or compromised client parts.

**Comment by BryanJacobs** [comment]
I'm not sure I understand exactly what you're saying.

Rephrasing what's in the documentation:

- Passive MITM (observation of traffic, no injection/modification) cannot steal the left16(sha256(PIN))
- Active MITM (modifying traffic) can steal the left16(sha256(PIN))
- If someone has left16(sha256(PIN)), they don't need to know your PIN to interact with the authenticator _as if_ they know your PIN

Malware on the client machine and compromised card readers are two examples of situations where an active MITM would be possible.

What are you looking to have changed in the documentation?

**Comment by nuno0529** [comment]
Yeah, I think the active MITM you defined here is more reasonable.  
Just my nitpicking here, from ctap2 spec, authenticators and clients doesn't have the way to do mutual authentication, so the MITM here should only mean there is a fake authenticator impersonate the original one to the client. And from the  authenticator's perspective, it's just passively talking to a client whether it's compromised or not.

**Comment by nuno0529** [comment]
Agree.
As the specs' disclaimer, the situations with using compromised clients/browsers (or w/ extensions) are always excluded in the scope. Just as new passwords managers' extensions with passkey support, it can even swallow the webauthn api.
