### ISSUE TITLE
0x33 in PIN verification

### ISSUE THREAD

**Issue by annu0412** [BryanJacobs/FIDO2Applet#34]
Installed applet then tried testing it on https://webauthn.io/
i got 0x33 "CTAP2_ERR_PIN_AUTH_INVALID" when tried authentication, registration was OK.
What am i doing wrong?

```
`Ctap Nfc SCardTransmit Request:

TransactionId: {29eeacbd-0a69-4655-811f-31954b9f9f67}
Reader: OMNIKEY CardMan 3x21 0

Request: 235 bytes
0x80100000E502A6016B776562617574686E2E696F025820B094FB9B8BB5410366134F72BFE7367E78CFF78E7E05CAFE5303FD5DAFD484C40381A26269645870F6006BB561B16CDE0200CE716C5F6185CE9CC941A2A27471F7BA3CA67D508746D82F94B10A51562BA30A5C5E6988070B1200F6A84F1C8A9BCCCBAB4E5F78250B65ADA5135BE58D809D4D84F797B0E52B769704DB2A176F1FC31307C6629F863341A463F79E27F98C9AF6E9461876D50464747970656A7075626C69632D6B657905A1627570F50658205689191B2099BACC14CB35244D7B49E886F0DD5497B4FE711448DE0ABEE4068D070200

Response data: 1 bytes
0x33

Apdu Status: 0x9000
`
```

**Comment by BryanJacobs** [comment]
The reason depends on how you built the applet.

If `ONE_USE_PER_PIN_TOKEN` or `WRITES_INVALIDATE_PINS` is set (default includes `WRITES_INVALIDATE_PINS`), you need to reinsert the smartcard after each usage. Registering would use up the PIN token, so Authenticating would then fail unless it's a fresh tap/insert.

This is due to the lack of a reliable user presence indicator on a smartcard.

**Comment by annu0412** [comment]
i am reinserting card but same, when i debugged i found out (see image below) 
`pinProtocol is 2` and `transientStorage.getPinProtocolInUse() is 0`

<img width="753" alt="image" src="https://github.com/user-attachments/assets/c7ac802a-0e78-41b4-9e67-ec8a424b35fc">

**Comment by BryanJacobs** [comment]
`getPinProtocolInUse()` being `0` means that no PIN authentication was done with the smartcard since the last time it was powered off/on. But parameter 0x07 (PIN protocol) was sent with the value `2` in your request and paramter 0x06 ( `pinUvAuthParam`) was set.

I can't tell you WHY that's happening, but it looks like your system thinks it has a valid PIN token but it does not. The correct response per the FIDO protocol in this situation is indeed PIN_AUTH_INVALID.

You may be able to work around the problem by enabling `alwaysUv` mode. That would likely cause the platform to prompt for your PIN every time, instead of assuming it could reuse a PIN token from before...

**Comment by annu0412** [comment]
Browser does ask for the PIN every time i try authenticate

**Comment by annu0412** [comment]
if possible could you please try at your end on same website?

**Comment by BryanJacobs** [comment]
I tested regularly with webauthn.io during development of this applet.

I just got this result using it installed on a P71 chip over NFC, using FidoK (my own library) as an HID bridge to Firefox.

![Screenshot 2024-10-21 at 20-09-12 WebAuthn io](https://github.com/user-attachments/assets/a1e605e9-974a-4f0c-9755-661145354ddb)

**Comment by annu0412** [comment]
i am using NXP P70 in a smartcard.
so here what i did..
Installed applet with no install param and then used it in webauthn.io
is above steps correct?

**Comment by BryanJacobs** [comment]
Those steps should be just fine. You're not trying to use it for U2F, so using no install parameters (for the defaults) should work.

In order to diagnose this further I need more of a trace than just the authenticate() operation. Could you please send the whole flow from the card insertion through the authentication? Specifically I need to see if a different applet is getting selected in the middle, which would wipe the transient storage...

Just to double check, you are using the _latest master_ from this repository, right? Like not a built artifact from Releases?

**Comment by BryanJacobs** [comment]
However you got the previous request is fine, just include the other SCardTransmit operations from when you insert the card until when auth fails.

**Comment by annu0412** [comment]
Below are the authentication logs...

```
Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 14 bytes
0x00A4040008A0000006472F000100

Response data: 8 bytes
0x4649444F5F325F30

Apdu Status: 0x9000

Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 7 bytes
0x80100000010400

Response data: 247 bytes
0x00B00183684649444F5F325F30684649444F5F325F316C4649444F5F325F315F50524502866375766D6863726564426C6F626B6372656450726F746563746B686D61632D7365637265746C6C61726765426C6F624B65796C6D696E50696E4C656E67746803500000000000000000000000000000000004AB62726BF5627570F466757641636667F568616C776179735576F468637265644D676D74F569617574686E72436667F569636C69656E7450696EF56A6C61726765426C6F6273F56E70696E557641757468546F6B656EF56F7365744D696E50494E4C656E677468F5706D616B654372656455764E6F74527164F5068202010717

Apdu Status: 0x6130

Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 5 bytes
0x80C0000030

Response data: 48 bytes
0x0818700A81A263616C672664747970656A7075626C69632D6B65790B1904000CF40D040E040F1820100212190200140C

Apdu Status: 0x9000


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 1 bytes
0x04

Response data: 295 bytes
0x00B00183684649444F5F325F30684649444F5F325F316C4649444F5F325F315F50524502866375766D6863726564426C6F626B6372656450726F746563746B686D61632D7365637265746C6C61726765426C6F624B65796C6D696E50696E4C656E67746803500000000000000000000000000000000004AB62726BF5627570F466757641636667F568616C776179735576F468637265644D676D74F569617574686E72436667F569636C69656E7450696EF56A6C61726765426C6F6273F56E70696E557641757468546F6B656EF56F7365744D696E50494E4C656E677468F5706D616B654372656455764E6F74527164F50682020107170818700A81A263616C672664747970656A7075626C69632D6B65790B1904000CF40D040E040F1820100212190200140C

Apdu Status: 0x9000


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 12 bytes
0x801000000606A20102020200

Response data: 81 bytes
0x00A101A501020338182001215820C340BCBFED23512B5D219775896EAE737E0B0D6539239F7ADABAC97D127DF595225820DCAA05B437C8F5CF1107F0D9F25ED1D8D393FDA2460B4369248C0707029A8805

Apdu Status: 0x9000


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 141 bytes
0x801000008706A60102020903A501020338182001215820776049139FF278F7A6DE0B7DC567D3A0CED81CCF4B460F2F0E128065BB44E0F1225820524B64994BD79356DA4EC372B6BC71522A842FE993644750196AD5077241070C0658201F8E8700392E1DE84617A78DA6855DD985FDC0F2566815FC9B77953A884E7C1309120A6B776562617574686E2E696F00

Response data: 53 bytes
0x00A10258301EF49DD76C1E94DCB951D4B6C36C75BF60B53CCB81F90A73846B36F949FD6973B12F8797EE36BECC3F22C3F1D3F571B4

Apdu Status: 0x9000


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 235 bytes
0x80100000E502A6016B776562617574686E2E696F0258209FAB007F44207F2C9BDAE468D2B6763E9C717FF87C7042A8B0222C6E83CE4C8F0381A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657905A1627570F40658208EEF2233A9433F4596966EE06DE1654B0A35BADEE643479331DA2837FCDD0C21070200

Response data: 252 bytes
0x00A401A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657902582574A6EA9213C99C2F74B22492B320CF40262A94C1A950A0397F29250B60841EF0040000002E035847304502204D5DF89D710606B53164584521BDA406AA03E84C37AC298CFB7A1F6140327B43022100F67926F8027CD1BB685190F02F2478D4427DE31FE31B208533BF85FEC08F744E04

Apdu Status: 0x613A


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 5 bytes
0x80C000003A

Response data: 58 bytes
0xA2626964582B52354A4E4E5962595035315359564E32656B52532D436D757A6C714856305158507A344F374F55576E3467646E616D6563313233

Apdu Status: 0x9000


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 229 bytes
0x02A6016B776562617574686E2E696F0258209FAB007F44207F2C9BDAE468D2B6763E9C717FF87C7042A8B0222C6E83CE4C8F0381A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657905A1627570F40658208EEF2233A9433F4596966EE06DE1654B0A35BADEE643479331DA2837FCDD0C210702

Response data: 310 bytes
0x00A401A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657902582574A6EA9213C99C2F74B22492B320CF40262A94C1A950A0397F29250B60841EF0040000002E035847304502204D5DF89D710606B53164584521BDA406AA03E84C37AC298CFB7A1F6140327B43022100F67926F8027CD1BB685190F02F2478D4427DE31FE31B208533BF85FEC08F744E04A2626964582B52354A4E4E5962595035315359564E32656B52532D436D757A6C714856305158507A344F374F55576E3467646E616D6563313233

Apdu Status: 0x9000


Ctap Nfc SCardTransmit Request:

TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
Reader: OMNIKEY CardMan 3x21 0

Request: 235 bytes
0x80100000E502A6016B776562617574686E2E696F0258209FAB007F44207F2C9BDAE468D2B6763E9C717FF87C7042A8B0222C6E83CE4C8F0381A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657905A1627570F50658208EEF2233A9433F4596966EE06DE1654B0A35BADEE643479331DA2837FCDD0C21070200

Response data: 1 bytes
0x33

Apdu Status: 0x9000



```

**Comment by BryanJacobs** [comment]
Excerpt from your logs below. My annotations are inline.

> TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
> Reader: OMNIKEY CardMan 3x21 0
> 
> Request: 12 bytes
> 0x801000000606A20102020200
> 
> Response data: 81 bytes
> 0x00A101A501020338182001215820C340BCBFED23512B5D219775896EAE737E0B0D6539239F7ADABAC97D127DF595225820DCAA05B437C8F5CF1107F0D9F25ED1D8D393FDA2460B4369248C0707029A8805
> 
> Apdu Status: 0x9000

This is getting the platform-authenticator shared secret (to secure the PIN as it's sent to the authenticator)

> 
> Ctap Nfc SCardTransmit Request:
> 
> TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
> Reader: OMNIKEY CardMan 3x21 0
> 
> Request: 141 bytes
> 0x801000008706A60102020903A501020338182001215820776049139FF278F7A6DE0B7DC567D3A0CED81CCF4B460F2F0E128065BB44E0F1225820524B64994BD79356DA4EC372B6BC71522A842FE993644750196AD5077241070C0658201F8E8700392E1DE84617A78DA6855DD985FDC0F2566815FC9B77953A884E7C1309120A6B776562617574686E2E696F00
> 
> Response data: 53 bytes
> 0x00A10258301EF49DD76C1E94DCB951D4B6C36C75BF60B53CCB81F90A73846B36F949FD6973B12F8797EE36BECC3F22C3F1D3F571B4
> 
> Apdu Status: 0x9000

This is sending the PIN to the authenticator and getting back a PIN token, successfully, with PIN protocol 2


> Ctap Nfc SCardTransmit Request:
> 
> TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
> Reader: OMNIKEY CardMan 3x21 0
> 
> Request: 235 bytes
> 0x80100000E502A6016B776562617574686E2E696F0258209FAB007F44207F2C9BDAE468D2B6763E9C717FF87C7042A8B0222C6E83CE4C8F0381A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657905A1627570F40658208EEF2233A9433F4596966EE06DE1654B0A35BADEE643479331DA2837FCDD0C21070200
> 
> Response data: 252 bytes
> 0x00A401A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657902582574A6EA9213C99C2F74B22492B320CF40262A94C1A950A0397F29250B60841EF0040000002E035847304502204D5DF89D710606B53164584521BDA406AA03E84C37AC298CFB7A1F6140327B43022100F67926F8027CD1BB685190F02F2478D4427DE31FE31B208533BF85FEC08F744E04
> 
> Apdu Status: 0x613A
>
> Ctap Nfc SCardTransmit Request:
> 
> TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
> Reader: OMNIKEY CardMan 3x21 0
> 
> Request: 5 bytes
> 0x80C000003A
> 
> Response data: 58 bytes
> 0xA2626964582B52354A4E4E5962595035315359564E32656B52532D436D757A6C714856305158507A344F374F55576E3467646E616D6563313233
> 
> Apdu Status: 0x9000

This is a successful getAssertion() call, passing a credential in as a parameter. The card returns a valid assertion for the name "123", which I'm guessing is what you typed into webauthn.io. Nothing failed.

> Ctap Nfc SCardTransmit Request:
> 
> TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
> Reader: OMNIKEY CardMan 3x21 0
> 
> Request: 229 bytes
> 0x02A6016B776562617574686E2E696F0258209FAB007F44207F2C9BDAE468D2B6763E9C717FF87C7042A8B0222C6E83CE4C8F0381A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657905A1627570F40658208EEF2233A9433F4596966EE06DE1654B0A35BADEE643479331DA2837FCDD0C210702
> 
> Response data: 310 bytes
> 0x00A401A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657902582574A6EA9213C99C2F74B22492B320CF40262A94C1A950A0397F29250B60841EF0040000002E035847304502204D5DF89D710606B53164584521BDA406AA03E84C37AC298CFB7A1F6140327B43022100F67926F8027CD1BB685190F02F2478D4427DE31FE31B208533BF85FEC08F744E04A2626964582B52354A4E4E5962595035315359564E32656B52532D436D757A6C714856305158507A344F374F55576E3467646E616D6563313233
> 
> Apdu Status: 0x9000
> 
> 
> Ctap Nfc SCardTransmit Request:
> 
> TransactionId: {af514eaf-7e88-4268-b560-a79801cbca20}
> Reader: OMNIKEY CardMan 3x21 0
> 
> Request: 235 bytes
> 0x80100000E502A6016B776562617574686E2E696F0258209FAB007F44207F2C9BDAE468D2B6763E9C717FF87C7042A8B0222C6E83CE4C8F0381A262696458703BFFC8B308E2978D52BD606E697B1D095239813F840574798369E9705930F4CB6FAB2CAD1A93B7B2B510FD938C193A5DB05F040727FACEF78F2645D2722AA9EAF42C557AA5019F9F5F22C613F78B87BD227425DCA14913AA50F0AFD897FAB54FA6032311FB1675C49D467241CC96216C64747970656A7075626C69632D6B657905A1627570F50658208EEF2233A9433F4596966EE06DE1654B0A35BADEE643479331DA2837FCDD0C21070200
> 
> Response data: 1 bytes
> 0x33
> 
> Apdu Status: 0x9000

This is a second attempt at a getAssertion(), using the same PIN token and credential as before. As the default options for the applet don't allow performing more than one operation per time the PIN token is fetched, this is rejected.

If you want to set `WRITES_INVALIDATE_PINS` to `false`, you may do so. That would let this pattern succeed, but also open up the possibility for replay attacks against your credentials on the card. That is a very minor threat, not a huge deal IMO.

If you want to figure out why Windows/Chrome is sending two copies of the getAssertion call and ignoring the first response, you may do that too. But the authenticator's behaviour here isn't incorrect so far as I can tell.

Thank you for providing the debug logs.

**Comment by BryanJacobs** [comment]
I have pushed new code to master that allows the form of preflighting shown by Windows in your logs (using the PIN token repeatedly with UP=false to getAssertion). I don't know why there are now three different ways to preflight credentials, but whatever.

Could you give it a try and see if it resolves your issue?
