### ISSUE TITLE
[BUG] J3H145 card crash

### ISSUE THREAD

**Issue by icedevml** [BryanJacobs/FIDO2Applet#5]
Something is very odd with J3H145 cards. One of the cards crashed entirely when I was testing the recent E-APDU fixes. Now I've took another card and loaded the master branch, it exhibits the same crash behavior. Steps to reproduce:

1. Register on https://demo.yubico.com/webauthn-technical/registration , that would create a normal FIDO2 authenticator (not resident credential)
2. Test authenticator on https://demo.yubico.com/webauthn-technical/login for once
3. Repeat step 1
4. Card goes entirely dead

I'm not able to talk to the card neither through contactless nor contact interface, it fails super early (on ISO 14443 selection). This doesn't happen with the exact same CAP file loaded on A40CR card.

For now I'm just dropping a report there, I need to order some more J3H145 cards and check if this is also reproducible.

**Comment by BryanJacobs** [comment]
This applet does basically nothing at all on a select, but yes, sending commands to the smartcard stops it from garbage collecting effectively.

I can't tell you that's what's going on, but still glad your card came "back to life". Note that the GC appears to only be necessary after a big applet install - I suspect that when these cards do a load-for-install they have a whole copy of the applet data waiting to be thrown away.

**Comment by icedevml** [comment]
Yeah I suspect that my workflow was to immediately take the card from the reader after the gradle build is finished. So I was not aware that this GC is not included in the install process itself. Sounds clear for now, I will be cautious around this. Thanks for your help!
