### ISSUE TITLE
FIDO 2.1 javacard applet for credProtect

### ISSUE THREAD

**Issue by sarabjeet2610** [BryanJacobs/FIDO2Applet#8]
First of all, thank you for providing the APDUS I requested in last issue. Much appreciated.

Could you help me out with the part of specification of FIDO 2.1 that you have referred to to implement the credProtect mechanism in the javacard applet that you have ? I am trying to understand the implementation but so far not able to find which part of specification refer for credProtect?

Again, your help is much appreciated on the matter

**Comment by BryanJacobs** [comment]
The specification is at https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-credProtect-extension .

You might be better off seeking help on Stackoverflow if you're doing something that is not related to this applet. If you are trying to get help with a relevant task, next time I will expect you to explain the task itself, so I can better assist you.
